--- 
title: "Infectious Disease Epidemiology<br>- a Model-based Approach (IDEMA)"
description: "A modern, model-based approach to infectious disease epidemiology"
author: "[Andreas Handel](https://www.andreashandel.com)"
date: "`r Sys.time()`"
site: bookdown::bookdown_site
url: "https://andreashandel.github.io/IDEMAbook/"
github-repo: "andreashandel/IDEMAbook"
output: 
  bookdown::gitbook:
    css: ./idemabook.css
    fig_caption: true
    keep_md: false
    config:
      edit: null
      toolbar:
        download: ["IDEMAbook.pdf", "docs/IDEMAbook.pdf"]
      toc:
        collapse: none
  bookdown::pdf_book:
    keep_tex: no
    toc: true
documentclass: book
bibliography: idemabook_references.bib
biblio-style: apalike
link-citations: yes
delete_merged_file: true
language:
  ui:
    chapter_name: "Chapter "
---

```{r, echo = FALSE, include = FALSE}
options(bookdown.render.file_scope = FALSE)
```

# Preface {-}

This book discusses infectious disease epidemiology using a model-based approach.

__Note 1: This book is a continuous work in progress. I will likely be moving material around, adding new chapters, combining existing ones, and adding more content. I don't expect to delete major parts, but rewrites and reshuffling are expected to keep happening. So if something you read previously is 'gone', it got likely moved to a different chapter/section of the book__  

Note 2: I appreciate receiving feedback. If you think a certain topic is missing that should be covered, or certain topics aren't explained well, or any other thought you have, please provide feedback. The best way of doing so is by going to [the github page for this book](https://github.com/andreashandel/IDEMAbook) and submitting an "Issue". Alternatively, feel free to email me (google me to get my email address).
