---
title: "Book proposal: Infectious Disease Epidemiology - A modern systems approach"
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
output:
  bookdown::word_document2: 
    toc: false
bibliography: ../../DSAIDEreferences.bib
---


# Author
* Andreas Handel^1^, Department of Epidemiology and Biostatistics, The University of Georgia, Athens, GA, USA


# Working book titles
* Infectious Disease Epidemiology - A modern systems approach
* Modern Infectious Disease Epidemiology - A (dynamical) systems approach


# Rationale and scope 

## Overview

Modern infectious disease (ID) epidemiology makes heavy use of computational model-based approaches and a dynamical systems perspective. The importance of analyzing infectious diseases in such a way keeps increasing. However, infectious disease epidemiology is still often taught mainly from a medical and classical epidemiological study design (e.g., cohort, case- control) perspective. A number of textbooks exist that approach infectious disease epidemiology from a classical epidemiological and medical perspective (e.g. [@magnus08; @nelson13; @giesecke17]).

While textbooks that teach a systems/model based approach to infectious diseases exist (e.g. [@anderson91; @diekmann00; @keeling08; @vynnycky10]), those books are meant to teach students how to become modelers. As such the books require students to work with mathematical models and write computer code. This is a significant barrier for students who do not have a strong mathematical background or prior coding experience, which applies to many students in public health and related biomedical disciplines. It limits the number of students who can or want to engage with infectious disease epidemiology by using modern, systems modeling-based approaches. 

I believe that anyone working on ID related topics in public health nowadays needs to have some familiarity with a model-based approach. There is currently (as far as I am aware) no book that teaches infectious disease epidemiology from a systems perspective while at the same time being approachable to students without the need of doing a good bit of math and/or computer programming. Thus the idea for this book. In this book, ID topics are discussed from a dynamical systems perspective, and make use of dynamical models. While some models and equations are shown, students should be able to follow the contents without a detailed understanding of the models/math. Students are not required to know advanced mathematics or coding and model building is not taught. The book does not try to teach the student to become a modeler. The focus is on understanding the modeling perspective and becoming an educated consumer of models. 





## Learning Objectives

The main goal of the book is to equip students with the knowledge to think about ID Epi in a systems way and to 'consume/interpret' results from infectious disease modeling studies. If students, after having worked through this book, want to proceed toward becoming modelers themselves, they could continue with the modeling textbooks mentioned above.

The proposed book is meant to address the following main learning objectives (more detailed objectives are listed at the beginning of each book chapter):

* Explain the importance of system dynamical thinking for the study and control of ID
* Understand how different stages of an infection play different roles influencing medical versus public health interventions
* Interpret the meaning and causes of specific dynamic patterns seen in ID incidence and prevalence 
* Explain and compute important epidemiological measures, such as reproductive number and level of herd immunity
* Know about main differences in ID transmission and how that affects control strategies
* Choose optimal ID intervention strategies based on features of specific IDs and predict the impact of different ID intervention strategies
* Understand how host heterogeneity impacts ID dynamics
* Appreciate the complexities of multi-pathogen dynamics
* Assess the role of stochasticity on ID extinction 
* Understand the mechanisms and drivers of pathogen evolution and the emergence of new infectious diseases
* Evaluate the impact of contact structure between hosts on ID transmission



## Specific Use Cases 
I envision several target groups and use cases for this book. The main target group are likely graduate (or possibly advanced undergraduate) students/courses in public health, epidemiology and related areas. In such a setting, this book might be used as follows:

* The main book for a course on ID Epi (to replace e.g. [@nelson13]), possibly supplemented with additional reading from the primary literature. This would be for a course that teaches ID Epi from a modern, dynamical systems perspective.
* One of the books used for a course on ID Epi, together with more classical books (e.g. [@nelson13]), to teach ID Epi in a mix of standard and model-thinking approach.
* The main book for a very introductory ID Modeling course, supplemented with further material (reading or exercises, especially the DSAIDE R package described below), to teach model building.
* One of the books used for an ID Modeling course, alongside e.g. [@keeling08; @vynnycky10]). 

Outside of the student/course setting, I hope this book might also be of use to professionals working broadly in the area of public health/epidemiology/infectious diseases in places like health departments, CDC, etc. Those individuals will have learned some ID Epi from a classical perspective (e.g. during their previous college degrees) and are increasingly exposed to model-based studies in the literature and want to better understand that approach, without wanting to become active modelers. For that target group, the book tries to provide a self-contained introduction to ID EPi from a modeling perspective.

## Use Case Examples 
As example, here is how we currently cover ID Epi at our institution (College of Public Health at the University of Georgia). We currently have 3 graduate level courses (with usually a mix of MPH/MS/PhD student enrolled) that broadly cover infectious diseases: 

1. Infectious Disease Epidemiology (taught by one of my colleagues for the last 5+ years), which uses a classical epidemiological/medical/disease centric approach with [@nelson13] as textbook. 
2. A course on Dynamical Systems Approaches to Infectious Disease Epidemiology which I have taught online for the last 2 years. The book described/proposed here originates from this class and is the main reading used. 
3. A course on Infectious Disease Modeling, also taught by myself for the last 5+ years, which in the past used [@keeling08; @vynnycky10] as recommended reading. Unfortunately, I found that both books require mathematical knowledge that many of my students could not handle. Thus the books were only optional/recommended (usually only a few students ended up buying one of them) and I mostly relied on my own materials. I am about to teach the modeling class again, and will point students to chaptes of the book as background reading, while we focus in the class on building and analyzing models. For those studetns that want to get deeply into the modeling literature I will continue to recommend [@keeling08; @vynnycky10] as optional further reading.

My colleague Isaac Fung at Georgia Southern University has also started to use the draft version of the book in his Infectious Disease Epidemiology Modeling class, alongside his current main textbook [@vynnycky10].

# Readership

The main audience are students in public health and related biomedical disciplines who want to learn about infectious disease epidemiology from a modern, systems-based perspective, while not (yet) wanting to engage deeply with the math and computational aspects related to the topic.

I assume readers are familiar with basic epidemiological and public health ideas such as incidence and prevalence, basic study design such as cohort and case-control studies and clinical trials, and other basic epidemiological concepts. I also assume readers have at least some passing knowledge of many infectious diseases, which make appearances in the book but are not described in much detail. 

It is likely that most readers will have some gaps (e.g. not being familiar with a specific disease or a specific epidemiological concept). Deep knowledge of any such topic is not required. Thus, filling such gaps does not require anything beyond some basic reading on main sources such as Wikipedia, the CDC website, or similar. Each chapter also provides links to further resources that can help fill any gaps, as well as point readers toward more advanced materials on a given topic if they decide to dig deeper.


# Competing/related books 
The rationale and scope sections above describe how I believe this book differs from existing classical ID EPi books ([@magnus08; @nelson13; @giesecke17]) and ID Modeling books ([@anderson91; @diekmann00; @keeling08; @vynnycky10]) and is positioned in the gap that I think exists between these two categories of currently existing ID Epi books.

Another book worth mentioning is [@kraemer10], which is an edited volume. It is a mix of ID topics, more conceptual/less medical than [@nelson13]. Since each chapter is written by a different set of authors, it has the usual problem of edited books that each chapter/topic is somewhat stand-alone, with authors writing at different levels of difficulty and discussing whatever they find relevant for a given topic. Thus the whole book is not that cohesive and I consider it suitable to assign specific chapters as additional reading but wouldn't use it as a stand-alone book for teaching/learning.

A somewhat older book similar to [@kraemer10] seems to be [@thomas01]. It is also an edited volume and based on the TOC, convers broadly similar ground to [@kraemer10]. I have not yet seen/reviewed the full text of [@thomas01].

To my knowledge, the resources that are most similar to the book in content/spirit are not textbooks but 2 online courses on Coursera, one called 'Epidemics - the dynamics of infectious diseases' developed by faculty from Penn State [@epimooc], and one called 'Epidemics', developed by faculty from Hong Kong University [@hkepidemics]. 

The Penn State course is 8 week long, features many very good and short videos, and is somewhat broader regarding content and discusses topics than my book. For instance 1 week of the course is devoted to within-host infection and immune response processes, something I do not cover explicitly. Almost all content is taught through the videos, with some optional reading drawn from the primary literature

The Hong Kong Course is 10 weeks long and also mainly video-based, with some optional reading drawn from the primary literature. The course discusses some topics my book doesn't touch on (e.g. communication strategies for ID interventions) while conversely I discuss topics (e.g. extinction and evolution) that are not/barely covered in the course.

Since different components of the online courses are taught by different instructors, my proposed book might be a bit more coherent. The book also contains exercises and is tightly integrated with my R package (see below). I consider the relation between these courses and my proposed book complementary, i.e. those are 2 different ways of teaching similar material, and I consider a combination of these courses (or select videos from the courses), and my book (and R package) the best way to cover the material. In my Dynamical Systems Approaches to Infectious Disease Epidemiology course, I generally assign both a chapter of my book and suitable videos from those online courses.


# Content 

A draft version of the book is currently available on Github at:

https://ahgroup.github.io/DSAIDEbook/

The current form of the book was written as part of my teaching of a course on this topic (the Dynamical Systems Approaches to Infectious Disease Epidemiology course mentioned above). This is an online graduate level course at the University of Georgia, taken mostly by Masters and PhD public health students and some students from other disciplines (e.g. Ecology, Veterinary Infectious Disease, Forestry, etc.). I have taught the course twice so far. The first year (fall 2016), I modified my previous lecture notes (based on the ID Modeling class I've been teaching for a while, as well as a short-term ID Epi class I taught previously at Emory University) and turned them into short readings for each topic. For the fall 2017 course, I combined those short readings and further expanded them, which eventually lead to the currently existing book draft. 

The book currently has the chapters listed below. Some chapters are already fairly complete, most are somewhat complete but still need further additions, a few chapters are in their early stages of development. Each chapter has the same structure, with a short section of suggested exercises at the end. In the last iteration of the course (fall 2017), each book chapter was covered in a week. Since then, I have added and rearranged the chapters somewhat. Additional materials I have used in this class are videos from the courses [@epimooc; @hkepidemics] described above, as well as papers from the primary literature. These materials are referenced in the 'further resources' section of each book chapter or are part of the exercises listed at the end of each chapter. Each week, students were assigned some or all of the exercises listed at the end of the chapter as weekly homework. Those exercises usually involve the DSAIDE R package described in more detail below, and suggestions for reading and critically discussing papers from the primary literature.

## Book Chapters

1. Overview of this book 
2. Introduction to the Dynamical Systems Approach 
3. Characterizing Infectious Disease States
4. Patterns of Infectious Disease Dynamics 
5. Reproductive Number 
6. Types of Infectious Disease Transmission 
7. Modes of Direct Transmission 
8. Environmental Transmission
9. Vector-borne ID Transmission 
10. Infectious Disease Control 
11. Infectious Disease Surveillance 
12. Host Heterogeneity 
13. Dynamics of Multiple Pathogens 
14. Stochastic Dynamics and Extinctions
15. Evolutionary Dynamics 
16. Evolution and Infectious Disease Control
17. Emerging Infectious Diseases 
18. Pathogen Virulence
19. Networks and Infectious Disease Transmission 
20. Summary 
21. Appendix A - A brief overview of modeling software
22. Appendix B - How to build or use the right model
23. Appendix C - The different uses of Infectious Disease models
24. Appendix D - A very brief introduction to data fitting
25. Appendix E - Glossary of terms


A complete table of contents can be found in the current book draft, which is provided as attachment.


# Description of ancillary material 
I have written an R package called DSAIDE that allows students to actively explore the topics covered in the book. This R package is freely available on CRAN (https://cran.r-project.org/package=DSAIDE). It consists of multiple simulations, wrapped into a graphical user interface (implemented in R/Shiny). Each app addresses a specific ID topic and comes with a description of the underlying model and a list of tasks for the user to do. The tasks are meant to explore and thus further learn the topic covered by an app.

This R package is fully developed and available on CRAN, I published a (freely available) paper in PLoS Comp Bio describing the package and its use [@handel17]. I have used this package in my previous teaching of the course, and know of at least 2 other colleagues (one at Virigina Tech, one at GA Southern) who have used the package as part of their ID Epi courses. 

While both the DSAIDE package and the book are designed such that they could be used on their own, in my opinion the combination of the 2 makes for the best learning experience. The idea is for a student to start by reading the material in the book. In the exercise section of each book chapter, the students are pointed toward the appropriate simulation in the DSAIDE package. Using the package and performing the given tasks for each app provides hands-on learning and further strengthens understanding of the material.

An important aspect of DSAIDE is its modular structure. The main intended use is through the graphical interface, which allows students with no coding experience to interact and explore infectious disease topics from a dynamical systems perspective. In addition, each app is written such that students have direct access to the underlying simulation code. This allows more advanced exploration by writing a few lines of their own code wrapped around the supplied simulation function, or even more advanced, by modifying the supplied simulation functions to suit their needs. As such, the package is useful for both students who wish to explore ID models but do not want to start writing code and building models, and those students who want to get a (gentle) introduction toward becoming active modelers. All of these details are described in more details in the PLoS Comp Bio paper mentioned above [@handel17]. 

Note that there are currently no apps in DSAIDE that directly deal with data (e.g. fitting dynamical models to time-series). This might change in the future, but fitting data is a more advanced topic and not the main focus of the DSAIDE package. It is also so technical that none of the introductory modeling textbooks thoroughly cover it. Neither will my book, apart from a very short introduction and overview in an appendix. The book talks about using data in combination with models, but does not explain the technicalities how that is actually done.

 
# Proposed length of the book and its proposed completion date 

Including TOC, references, figure captions and everyhing, I crude word count gives around 35,000 words ad 110 pages in Microsoft Word. I expect the final version to be roughly double. My aspirational completion date for a first draft is end of summer 2019. 


# Planned next steps

* I plan to compile a list of ID Epi courses (and related) taught across higher education institutions and find out who teaches what and what teaching resources (books, etc.) they currently use. Based on that, I'll adjust my book to ensure it fills perceived gaps. I have started such a list.
* I want to re-visit various pertinent books/courses/resources and review them to see if there are any topics that I think should be added to my book. 
* All existing chapters need further work. Some require more text content, most require additional figures/graphs/examples. Some figures might need to be replaced/removed for copyright reasons.
* Further resources and Exercises sections of each chapter need to be worked on.
* Objectives for each chapter need to be fully aligned with content and made consistent across Bloom's Taxonomy.
* Everything needs further editing and cleaning up.


# Brief credentials of the author

Andreas Handel    
Associate Professor    
Assoc. Dept. Head &    
Graduate Coordinator    
Department of Epidemiology and Biostatistics    
College of Public Health, University of Georgia    
Athens, Georgia 30602, USA    
http://handelgroup.uga.edu/    

See website for my research and further information.


# Some other comments
Color figures are likely not needed, but might be nice for the online version of the book. The book contains text boxes that are set apart from the main text and that contain more advanced material (e.g. show sets of differential equations) that students can skip without losing the ability to understand the rest. 

The book is written in bookdown (https://bookdown.org/) and lives in the "R ecosystem" (markdown, pandoc, bibtex, etc.)




# References



